#include <uclib/mheap.c>
#include <uclib/format.c>
#include <uclib/std-formats.c>
#include <uclib/unformat.c>
#include <uclib/error.c>
#include <uclib/fifo.c>
#include <uclib/os.c>
#include <uclib/vec.c>
#include <uclib/hash.c>
#include <uclib/backtrace.c>
#include <uclib/smp.c>
#include <uclib/mem_mheap.c>
